<?php

namespace App\Enums;

enum Persistence: string
{
    case CREATE = "CREATE";
    case UPDATE           = "UPDATE";
    case REMOVE           = "REMOVE";
    case CREATE_OR_UPDATE = "CREATE_OR_UPDATE";
    case FIND_ONE_BY_ID = "FIND_ONE_BY_ID";
    case FIND_ALL        = "FIND_ALL";
    case REMOVE_MULTIPLE = "REMOVE_MULTIPLE";
    case DAR_BAIXA = "DAR_BAIXA";
    case DAR_BAIXA_MULTIPLE = "DAR_BAIXA_MULTIPLE";

    case DESFAZER_PAGAMENTO = "DESFAZER_PAGAMENTO";
    case DESFAZER_PAGAMENTO_MULTIPLE = "DESFAZER_PAGAMENTO_MULTIPLE";

    case NOTIFICAR_COBRANCA_ASAAS = "NOTIFICAR_COBRANCA_ASAAS";
    case NOTIFICAR_COBRANCA_ASAAS_MULTIPLE = "NOTIFICAR_COBRANCA_ASAAS_MULTIPLE";

    case RENOVAR_UMA_MATRICULA = "RENOVAR_UMA_MATRICULA";

    case CRIAR_MATRICULAS_MULTIPLOS_ALUNO = "CRIAR_MATRICULAS_MULTIPLOS_ALUNO";

}
